### ISSUE TITLE
NSWindowStyleMaskDocModalWindow inner webview hover not work

### ISSUE THREAD

**Issue by yvanwangl** [o2team/sketch-plugin-boilerplate#1]
当设置 `panel.setStyleMask(NSWindowStyleMaskDocModalWindow)` 后会导致嵌入的 webview 中的 hover 事件失效，这个问题有解决办法吗？

**Comment by pfan123** [comment]
`panel.setStyleMask(NSWindowStyleMaskDocModalWindow)`， 设置是为了让 `webview` 不为圆角，并不会导致 hover 失效，认真检查一下，是否网页有设置
