### ISSUE TITLE
sketch 70 版本，插件侧边栏打不开

### ISSUE THREAD

**Issue by janily** [o2team/sketch-plugin-boilerplate#15]
插件侧边栏，sketch 70 版本下，插件打不开哦

**Comment by Dawn-King** [comment]
版本70.3 (109109)，也打不开。

**Comment by snakeUni** [comment]
@Dawn-King @janily 可以参考这个 https://sketchplugins.com/d/2221-sidebar-error-in-sketch-v70/9

**Comment by tianyuya** [comment]
有修复么，71版本也打不开

**Comment by pfan123** [comment]
> 有修复么，71版本也打不开

fixed

**Comment by gluu1** [comment]
> 有修复么，71版本也打不开

@janily @Dawn-King @tianyuya    已修复
