### ISSUE TITLE
Long time running script

### ISSUE THREAD

**Issue by yvanwangl** [o2team/sketch-plugin-boilerplate#2]
由于侧边工具的按钮存在交互逻辑，需要在后台运行一个保活进程阻止sketch GC，例如：
`COScript.currentCOScript().setShouldKeepAround(true)`  或者 
```
import sketchAsync from 'sketch/async';
const fiber = sketchAsync.createFiber();
```
然后在 onCloseDocument 事件中关闭保活进程
```
export const onCloseDocument = () => {
  COScript.currentCOScript().setShouldKeepAround(false)
}

```
但是如果用户长时间不关闭sketch就会导致侧边工具栏多个按钮不互斥，以及一些api失效的问题，怀疑是因为长时间没有进行 GC 导致的，不知道有没有排查思路和解决思路？

**Comment by pfan123** [comment]
🤣 🤣，没遇到所说的这种情况，我理解 `COScript.currentCOScript().setShouldKeepAround(true)` 与 `COScript.currentCOScript().setShouldKeepAround(false)`  只是来做 sketch  内存管理的，会影响执行效率开发调试，并不会从逻辑上导致侧边工具栏多个按钮不互斥、api失效
