### ISSUE TITLE
69版本和70版本的兼容性

### ISSUE THREAD

**Issue by xusang** [o2team/sketch-plugin-boilerplate#24]
document.splitViewController().insertSplitViewItem_atIndex这个api在70版本以下发现没有，在70版本以上存在，是否需要判断版本使用不同的方法？
还有一个小问题是如何获取侧边栏的frame，因为想要获取坐标和长宽等值。
感谢

**Comment by gluu1** [comment]
> document.splitViewController().insertSplitViewItem_atIndex这个api在70版本以下发现没有，在70版本以上存在，是否需要判断版本使用不同的方法？
> 还有一个小问题是如何获取侧边栏的frame，因为想要获取坐标和长宽等值。
> 感谢

参考下这部分的 commit，70版本以下是通过获取 contentView 进行遍历进行插入 panel 的， 同时遍历也可以看到侧边栏的frame
https://github.com/o2team/sketch-plugin-boilerplate/commit/9fde90ed1b3e7bca64d2d581f92f153d46cba1cd#diff-60343dc612e9f63d87bde54a78de992408a40240b5511f7075969b3ee6a7ed53

**Comment by xusang** [comment]
好的 非常感谢 我把侧边栏的菜单也改成了webview的方式
