### ISSUE TITLE
webview 中 input 不能获取鼠标焦点事件，无法输入内容

### ISSUE THREAD

**Issue by janily** [o2team/sketch-plugin-boilerplate#6]
我在本地使用 webview 中使用 input ，鼠标点击不能获取焦点，不能输入内容哎，麻烦帮忙看看。
<img width="363" alt="屏幕快照 2020-04-24 上午11 49 24" src="https://user-images.githubusercontent.com/1013557/80173221-b3fd8300-8621-11ea-9381-557e36720b2b.png">

**Comment by pfan123** [comment]
应该是你开webview 页面设置有问题吧，这个需要你自己解决

**Comment by janily** [comment]
> 应该是你开webview 页面设置有问题吧，这个需要你自己解决

我没做任何设置哎，我直接使用这个模板，input 也是不能获取焦点输入的，我的 sketch 版本是 63.1

**Comment by oimz1989** [comment]
> > 应该是你开webview 页面设置有问题吧，这个需要你自己解决
> 
> 我没做任何设置哎，我直接使用这个模板，input 也是不能获取焦点输入的，我的 sketch 版本是 63.1

这个问题后来解决了么，我也遇到了

**Comment by janily** [comment]
> > > 应该是你开webview 页面设置有问题吧，这个需要你自己解决
> > 
> > 
> > 我没做任何设置哎，我直接使用这个模板，input 也是不能获取焦点输入的，我的 sketch 版本是 63.1
> 
> 这个问题后来解决了么，我也遇到了

这个问题你解决了么，我这直接使用这个模板没做任何设置，input 还是不能获取焦点输入文字

**Comment by snakeUni** [comment]
> > > > 应该是你开webview 页面设置有问题吧，这个需要你自己解决
> > > 
> > > 
> > > 我没做任何设置哎，我直接使用这个模板，input 也是不能获取焦点输入的，我的 sketch 版本是 63.1
> > 
> > 
> > 这个问题后来解决了么，我也遇到了
> 
> 这个问题你解决了么，我这直接使用这个模板没做任何设置，input 还是不能获取焦点输入文字. sketch 升级到最新到 69 Mac 系统是 10.4.6 也不行 @pfan123 可以帮忙看看么

> this.browserWindow._panel.setStyleMask(NSWindowStyleMaskDocModalWindow) 注释掉这行代码
